module.exports.descriptors = [
    'Maxo',
    'Ancient',
    'Petrified',
    'Apollo',
    'Cascade',
    'Tumbling',
    'Silent',
    'Red Hill',
    'Bull ',
    'Maple',
    'Misty',
    'Elk',
    'Grizzly',
    'Ocean',
    'Sea',
    'Sky',
    'Dusty',
    'Diamond'
]

module.exports.places = [
    'Tanuj Rawat Medical Shop',
    'Village Medical Shop',
    'Canyon Medical Shop',
    'Pond Medical Shop',
    'Group Medical Shop',
    'Horse Medical Shop',
    'Ghost Town Medical Shop',
    'Medx Shop',
    'Dispersed Medical Shop',
    'Backcountry Medical Shop',
    'River Medical Shop',
    'Creek Medical Shop',
    'Creekside Medical Shop',
    'Bay Medical Shop',
    'Spring Medical Shop',
    'Bayshore Medical Shop',
    'Sands Medical Shop',
    'Mule Shop Medical Shop',
    'Hunting Shop Medical Shop',
    'Cliffs Medical Shop',
    'Hollow Medical Shop'
]